### ISSUE TITLE
build_ctags causes a compile error on newer beta versions

### ISSUE THREAD

**Issue by AlecGoncharow** [rluba/jai-ctags#1]
Hello! 

I am one of the new additions to the beta and am bumbling my way through getting my tooling setup. 

It seems that `compiler_get_current_workspace()` has been dropped in favor of `get_current_workspace()` in the Preload module.

I changed it on my local copy and it seems to compile fine but something else is wrong and I don't get any output, so it felt disingenuous to raise a 1 line PR that doesn't actually fix anything. 

I can keep poking around but it seems this isn't function isn't meant to be used for real use cases anyways.

**Comment by sir-pinecone** [comment]
Got it working again https://github.com/sir-pinecone/jai-ctags/commit/6f6b071
I just got access to the beta though, so I might be doing something dumb. For example, I'm not sure why the current workspace is 2 now instead of 1. Is that to be expected?

**Comment by rluba** [comment]
Sorry guys, I didn’t see the original GitHub notification. (Don’t know what's wrong there… I seem to miss most of them.)

I just fixed it and added a small example.
